// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvbyijqexkaleadgvohb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2YnlpanFleGthbGVhZGd2b2hiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NDQ3MjcsImV4cCI6MjA2NDQyMDcyN30.CdWrrYEnptS9Ul36tUDFLAlOohN5hjJ21sGEdjNhLbY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);